# Generated by Django 5.2.17 on 2026-09-14 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill_skills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
