# Generated by Django 5.2.17 on 2026-09-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming Languages'), ('web', 'Web Development'), ('game', 'Game Development'), ('database', 'Database'), ('systems', 'Systems & Networking'), ('tools', 'Tools & Technologies'), ('other', 'Other')], default='programming', max_length=20),
        ),
    ]
